### ISSUE TITLE
Projede download parametresi olsa nasıl olur?

### ISSUE THREAD

**Issue by CihatAltiparmak** [r0ark/pms#5]
Aklımda --download diye bir arguman eklemek geldi ama şu anlık kafamda taslak oluşturamadıgım için yapmadım.Yapabilirsem boyle bir şey yapmayı düşünüyorum şimdilik.Boyle bir şey yapılsa nasıl olur sizce?Eger boyle bir şey eklemek isterseniz siz de yapmaya çalışın,ben de yapmaya çalışırım.Yapmak istemiyorsanız sorun degil.

Kolay gelsin :)

**Comment by r0ark** [comment]
Bu download parametresinin işlevi ne olacak?

**Comment by CihatAltiparmak** [comment]
Atıyorum ben bir github reposunu indirmek istedim, tamam,biliyorum git clone var ama sadece ornek olsun diye anlatıyorum.Ben githubdaki dosyaları bu parametre sayesinde çekebileceğim mesela.Biliyorum,anlatamadım, belki de saçma,ama akılda en azından bir taslak oluşur diye boyle soyledim.

**Comment by r0ark** [comment]
[https://github.com/r0ark/pms/archive/master.zip](https://github.com/r0ark/pms/archive/master.zip) 
GitHub, bir repoyu yukarıdaki gibi bize sunuyor indirebilmemiz için. Gereksiz olacağı kanısındayım böyle bir fonksiyonun, projenin amacı bir projeyi **ana bilgisayardan** farklı cihazlara aktarmayı kolaylaştırmak. Teşekkür ediyorum yine de :)
